"use strict";

import React from 'react';
import {Button,
    Toast,
    TextArea,
    ButtonArea,
    Form,
    FormCell,
    CellHeader,
    Label,
    Input,
    Cells,
    Cell,
    CellFooter,
    Dialog,
    CellBody
} from 'react-weui';
const { Confirm } = Dialog;
import Page from '../../component/page';
import {Tool,Alert} from '../../tool.js';
import './index.less';
import {LoadAd,NoMor,NoDataS} from '../../component/more.js';
import ShowAlert from '../../component/Alert.js';

class Inquire extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            type:'',
            data:{},
            error:false,
        };

    }
    componentWillMount(){ 
        let infoData = Tool.localItem('infoData');
        let InquireDatas = Tool.localItem('InquireDatas')
        if(infoData){
            this.setState({
                data:JSON.parse(infoData).data.AnnouncementDetail || JSON.parse(infoData).data.chassismodel || JSON.parse(infoData).data.FuelOilDetail
            })
        }else{
            this.setState({
                error:true
            })          
        }
        if(InquireDatas){
            this.setState({
                type:JSON.parse(InquireDatas).type
            })            
        }else{
            this.setState({
                error:true
            })             
        }
    }
    componentDidMount() {
        if(this.state.error){
            Alert.to('加载错误...');
            this.context.router.push({pathname: '/inquireResult'})
        }
    }

    render() {
        let data = this.state.data;
        if(this.state.type == 2){
            console.log(data,'data')
            return(
                <div className="inquireResultInfo">
                    <div className="product-img">
                        <img src={data.picture.length ? data.picture[0] : 'http://static.360che.com/gonggao/default360.jpg'}/>
                    </div>  
                    <header className="title">
                        车型
                    </header> 
                    <FormCell>
                        <CellHeader>
                            车型型号(产品型号)
                        </CellHeader>
                        <CellBody>
                            {data.promodel}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            车型名称(产品名称)
                        </CellHeader>
                        <CellBody>
                            {data.proname}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            品牌
                        </CellHeader>
                        <CellBody>
                            {data.brand}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            企业名称
                        </CellHeader>
                        <CellBody>
                            {data.company}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            公告批次
                        </CellHeader>
                        <CellBody>
                            {data.pcsn}
                        </CellBody>
                    </FormCell>  
                    <FormCell>
                        <CellHeader>
                            整车车型
                        </CellHeader>
                        <CellBody>
                            {data.protype}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            外形尺寸(长×宽×高)mm
                        </CellHeader>
                        <CellBody>
                            {data.shapesize}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            货厢栏板内尺寸(长×宽×高) mm或容积m3
                        </CellHeader>
                        <CellBody>
                            {data.innersize}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            载客人数
                        </CellHeader>
                        <CellBody>
                            {data.personnum}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            牵引座最大允许承载质量kg
                        </CellHeader>
                        <CellBody>
                            {data.maxload}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            整备质量KG
                        </CellHeader>
                        <CellBody>
                            {data.zbweight}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            总质量 kg
                        </CellHeader>
                        <CellBody>
                            {data.weight}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            驱动形式
                        </CellHeader>
                        <CellBody>
                            {data.drivermodel}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            底盘厂家
                        </CellHeader>
                        <CellBody>
                            {data.pancompany}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            底盘型号
                        </CellHeader>
                        <CellBody>
                            {data.panmodel}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            发动机厂家
                        </CellHeader>
                        <CellBody>
                            {data.enginecompany}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            发动机型号
                        </CellHeader>
                        <CellBody>
                            {data.enginemodel}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            变速箱
                        </CellHeader>
                        <CellBody>
                            {data.bsqmodel}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            主减速器对比(驱动桥速比)
                        </CellHeader>
                        <CellBody>
                            {data.jsqrate}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            轮胎规格型号
                        </CellHeader>
                        <CellBody>
                            {data.tyremodel}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            综合燃料消耗量L/100km
                        </CellHeader>
                        <CellBody>
                            {data.avecost}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            60km/h空载等速燃料消耗量L/100km
                        </CellHeader>
                        <CellBody>
                            {data.emptycost}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            执行标准
                        </CellHeader>
                        <CellBody>
                            {data.prostd}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                            燃油消耗量达标车型编号
                        </CellHeader>
                        <CellBody>
                            {data.prosn}
                        </CellBody>
                    </FormCell>  
                </div>          
                
            )
        }else{
            return (
                <div className="inquireResultInfo">
                    <div className="product-img">
                        <img src={data.picture.length ? data.picture[0] : 'http://static.360che.com/gonggao/default360.jpg'}/>
                    </div>
                    <header className="title">
                        车型
                    </header>
                    <FormCell>
                        <CellHeader>
                            公告标题
                        </CellHeader>
                        <CellBody>
                            {data.title}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           公告号
                        </CellHeader>
                        <CellBody>
                            {data.model}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           公告批次
                        </CellHeader>
                        <CellBody>
                            {data.pcsn}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           品牌
                        </CellHeader>
                        <CellBody>
                           {data.brand}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            车型
                        </CellHeader>
                        <CellBody>
                            {data.protype}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           额定质量
                        </CellHeader>
                        <CellBody>
                            {data.edweight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           总质量
                        </CellHeader>
                        <CellBody>
                            {data.totalweight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           整备质量
                        </CellHeader>
                        <CellBody>
                           {data.zbweight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            燃料种类
                        </CellHeader>
                        <CellBody>
                            {data.fueltype}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           排放依据标准
                        </CellHeader>
                        <CellBody>
                            {data.pfstd}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           轴数
                        </CellHeader>
                        <CellBody>
                            {data.zhoushu}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           轴距
                        </CellHeader>
                        <CellBody>
                           {data.zhouju}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            轴荷
                        </CellHeader>
                        <CellBody>
                            {data.zhouhe}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           弹簧片数
                        </CellHeader>
                        <CellBody>
                            {data.thpnum}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           轮胎数
                        </CellHeader>
                        <CellBody>
                            {data.tyrenum}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           接近离去角
                        </CellHeader>
                        <CellBody>
                            {data.liqujiao}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           前悬后悬
                        </CellHeader>
                        <CellBody>
                           {data.qianhouxuan}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            前轮距
                        </CellHeader>
                        <CellBody>
                            {data.qianlunju}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           后轮距
                        </CellHeader>
                        <CellBody>
                            {data.houlunju}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           识别代号
                        </CellHeader>
                        <CellBody>
                            {data.sbsn}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           整车长
                        </CellHeader>
                        <CellBody>
                           {data.trucklength}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                            整车宽
                        </CellHeader>
                        <CellBody>
                            {data.truckwidth}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           整车高
                        </CellHeader>
                        <CellBody>
                            {data.truckheight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           货厢长
                        </CellHeader>
                        <CellBody>
                            {data.boxlength}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           货厢宽
                        </CellHeader>
                        <CellBody>
                           {data.boxwidth}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           货厢高
                        </CellHeader>
                        <CellBody>
                           {data.boxheight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           最高车速
                        </CellHeader>
                        <CellBody>
                            {data.maxrate}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           额定载客
                        </CellHeader>
                        <CellBody>
                           {data.peoplenum}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           驾驶室准乘人数
                        </CellHeader>
                        <CellBody>
                            {data.drivernum}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           转向形式
                        </CellHeader>
                        <CellBody>
                           {data.turntype}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           准拖挂车总质量
                        </CellHeader>
                        <CellBody>
                           {data.gcweight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           载质量利用系数
                        </CellHeader>
                        <CellBody>
                            {data.useratio}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           半挂车鞍座最大承载质量
                        </CellHeader>
                        <CellBody>
                           {data.maxczweight}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           企业名称
                        </CellHeader>
                        <CellBody>
                           {data.factory}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           企业地址
                        </CellHeader>
                        <CellBody>
                            {data.address}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           电话号码
                        </CellHeader>
                        <CellBody>
                           {data.telephone}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           传真号码
                        </CellHeader>
                        <CellBody>
                           {data.fax}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           邮政编码
                        </CellHeader>
                        <CellBody>
                            {data.postcode}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           底盘1
                        </CellHeader>
                        <CellBody>
                           {data.chassis1}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           底盘2
                        </CellHeader>
                        <CellBody>
                           {data.chassis2}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           底盘3
                        </CellHeader>
                        <CellBody>
                           {data.chassis3}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           底盘4
                        </CellHeader>
                        <CellBody>
                           {data.chassis4}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           描述
                        </CellHeader>
                        <CellBody>
                           {data.remarks}
                        </CellBody>
                    </FormCell>  
                    <FormCell>
                        <CellHeader>
                           发动机型号
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[0] : ''}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                           发动机型号
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[0] : ''}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                           发动机生产企业
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[1] : ''}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                           发动机商标
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[2] : ''}
                        </CellBody>
                    </FormCell> 
                    <FormCell>
                        <CellHeader>
                           发动机排量
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[3] : ''}
                        </CellBody>
                    </FormCell>
                    <FormCell>
                        <CellHeader>
                           发动机功率
                        </CellHeader>
                        <CellBody>
                           {data.engine.length ? data.engine[4] : ''}
                        </CellBody>
                    </FormCell>                             
                    <ShowAlert />
                </div>
            )            
        }

    }
};

Inquire.contextTypes = {
    router: React.PropTypes.object.isRequired
}

export default Inquire 
